language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: jJ6OUPoBhw3WtxZ0Il/h94eVCC4wi3Oadu1VQT+dxJ9Xi6edDHmovKSqHJ53fnj4qUCxMaQV4VD0EcOv0vmJZe17C98MekjuSPbjDc1VHXkM+iuPysj/Dhgk0cI6lo/oMxTFJDLvHFgjDAaIBygWrTAgXh43ptc695WVbomub2pswQX+4v/zIE9hZZwTkLoDkNL8lP1HYODWB0ZQ5+qOv4mR4XBUwTEN4CO98WzJmlM1TWrcHj6X3Tr+sIzAUII6Nlwk8c9I6mUvFS3btY6JBYTsK545YHn6cyth0w125PcXKtb3tnzOU2SgH1vJ5WBZjzvWKf2uFGV2nNwnUJ4CAf2OsOSD0BAw3exTXch7fRjzy9AlWoDah86ubKSCbddCxcrq5z520vECGA6M3eyVKnjgXZRoUQmmtgOezQTXWD4JQ8SAjoxaq9RgzjKcPbOwRcNJo6qskjEgyoOS0Xta3MKgkAV0HSb3DNEK5oK+3WCC13yejj3TPhSNf3H7O0eUxqmWJhZQV5LhEqAHUFRCLUuWzdFcq33e4B9AluJInLLUXAmAaz8/FCXQDw+C/8NZuSKYuy8W9HgKkGJvjL75HFiZxOOEpHShOwJLfxuzzXJDBUXl5cSLkNLkVHHc8x8NKOzaCazcXFNwpp1vHXr0bQUXmSlpXZwtDQ0LD0Bt6BA=
  app: ancient-waters-26676
  on:
    repo: Michaela-M/blog-app-tests
