language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: NJO1J4Jdk4MbykziDa3SdLF9udCtEaJQS9HL2xLajgTj+K+j6/A3pfATLH9CZxg6IdI5S9BwJRviyWWVQVNug/16gfSNehoLrpxXKJbX8rEdfd+qq7Zgs7XAcLMwX2YyAP3f0gGp9oohhXx2y9YdkSYrNerjHlT38vqlpdO1w8TsqDRm5bJMjRYnP83yedDNJFpstZKnOLYeQMmrFOnx+LoL9pwKcGTXQOHVz5CkatFTgjB2SzV2blOL/tT4GnOvBYyZkPOgjs2OCM/e95rcbldfmxypVgOu5JqoFcBM/F+UasrjcZsBUzb6f3KvLJaUPHKznaCgpLPalVr5Q/rhYZY6DOh9x87fojGXuvVP6BtXZkJc0xS5svCr6rU7KsTtstxwd0pjvpOAbgRx4O+K8NGAckOdg6F5Lvj4yeVbYF91aOhJhkSGal0QG2jgB+5/+m64CMBTakr/w/Dj5JmCLY4u9+n1auQBjPNOcEJOfmXjheOckY9LUaTdN/k2AX2EPh5SCtLgYECEJEj/BZkMN9KOR6+KlAL8bn1WZ60YAjYYPBN1+HrDg+PxB1l3yMYpBuaEi30EAwCl+ojwNuIlJMhoTDoSFPfiK3+TKn5ye6c+Dp1cgkakkd1W1aknSGRaQEtAKI++hSVeUqg6u8FJrk5jhCxWvCaYTXnAFa0T0WQ=
  app: ancient-waters-26676
  on:
    repo: Michaela-M/blog-app-tests
